name: Build and Package SmartTranslateAi

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: SmartTranslateAi-Windows.zip
            asset_path: dist/SmartTranslateAi.exe
          - os: ubuntu-latest
            artifact_name: SmartTranslateAi-Linux.tar.gz
            asset_path: dist/SmartTranslateAi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyside6 aiohttp python-dotenv

      - name: Build with PyInstaller
        run: |
          # ساخت فایل اجرایی
          pyinstaller --name "SmartTranslateAi" --windowed --noconsole --onefile --noconfirm --clean app/main.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/SmartTranslateAi.exe
            dist/SmartTranslateAi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
